all: plot kolejka_zdarzen mouse dynablaster
	# Done
plot: plot.cpp
	g++ plot.cpp -o plot -I/usr/local/include/ -L/usr/local/lib -lallegro -lallegro_main -lallegro_primitives
kolejka_zdarzen: kolejka_zdarzen.cpp
	g++ kolejka_zdarzen.cpp -o kolejka_zdarzen -I/usr/local/include/ -L/usr/local/lib -lallegro -lallegro_main -lallegro_primitives
mouse: mouse.cpp
	g++ mouse.cpp -o mouse -I/usr/local/include/ -L/usr/local/lib -lallegro -lallegro_main -lallegro_primitives
dynablaster: dynablaster.cpp
	g++ dynablaster.cpp -o dynablaster -I/usr/local/include/ -L/usr/local/lib -lallegro -lallegro_main -lallegro_primitives -lallegro_image
